### ISSUE TITLE
启动崩溃 java.lang.SecurityException: Binder invocation to an incorrect interface

### ISSUE THREAD

**Issue by mcmy** [gitofleonardo/AnyDebug#24]
添加XServiceManager.debug(true)
异常位置：XServiceManager.getService报null
com.hhvvg.anydebug.ui.fragment.SettingsFragment 第24行
val binder = XServiceManager.getService(CONFIGURATION_SERVICE)
获取binder为null
错误日志
2022-11-28 16:56:42.777 24149-24149 XServiceManager         com.hhvvg.anydebug                   E  get CONFIGURATION_MANAGER_SERVICE service error
                                                                                                    java.lang.SecurityException: Binder invocation to an incorrect interface
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at com.kaisar.xservicemanager.XServiceManager.getService(XServiceManager.java:250)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment$confService$2.invoke(SettingsFragment.kt:25)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment$confService$2.invoke(SettingsFragment.kt:23)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.getConfService(SettingsFragment.kt:23)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreatePreferences(SettingsFragment.kt:48)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreate(SettingsFragment.kt:37)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
                                                                                                    	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1913)
                                                                                                    	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
                                                                                                    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
                                                                                                    	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
                                                                                                    	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1098)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
                                                                                                    	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:61)
                                                                                                    	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:55)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity.getBinding(MainActivity.kt:11)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity.onCreate(MainActivity.kt:15)
2022-11-28 16:56:42.777 24149-24149 XServiceManager         com.hhvvg.anydebug                   E  	at android.app.Activity.performCreate(Activity.java:8463)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8432)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8109)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at android.os.Parcel.nativeEnforceInterface(Native Method)
                                                                                                    	at android.os.Parcel.enforceInterface(Parcel.java:918)
                                                                                                    	at android.content.IClipboard$Stub.onTransact(IClipboard.java:175)
                                                                                                    	at com.android.server.clipboard.ClipboardService$ClipboardImpl.onTransact(ClipboardService.java:355)
                                                                                                    	at android.os.Binder.transact(Binder.java:1169)
2022-11-28 16:56:42.778 24149-24149 AndroidRuntime          com.hhvvg.anydebug                   D  Shutting down VM
2022-11-28 16:56:42.779 24149-24149 AndroidRuntime          com.hhvvg.anydebug                   E  FATAL EXCEPTION: main
                                                                                                    Process: com.hhvvg.anydebug, PID: 24149
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hhvvg.anydebug/com.hhvvg.anydebug.ui.MainActivity}: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8109)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
                                                                                                    Caused by: java.lang.NullPointerException: <get-confService>(...) must not be null
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.getConfService(SettingsFragment.kt:23)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreatePreferences(SettingsFragment.kt:48)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
                                                                                                    	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreate(SettingsFragment.kt:37)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
                                                                                                    	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1913)
                                                                                                    	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
                                                                                                    	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
                                                                                                    	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
                                                                                                    	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
                                                                                                    	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
2022-11-28 16:56:42.779 24149-24149 AndroidRuntime          com.hhvvg.anydebug                   E  	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
                                                                                                    	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1098)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
                                                                                                    	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:61)
                                                                                                    	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:55)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity.getBinding(MainActivity.kt:11)
                                                                                                    	at com.hhvvg.anydebug.ui.MainActivity.onCreate(MainActivity.kt:15)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8463)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8432)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8109)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by gitofleonardo** [comment]
需要勾选系统框架，然后重启手机
