### ISSUE TITLE
MIUI14 启动崩溃

### ISSUE THREAD

**Issue by PandaQuQ** [gitofleonardo/AnyDebug#25]
空指针
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hhvvg.anydebug/com.hhvvg.anydebug.ui.MainActivity}: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: android.view.InflateException: Binary XML file line #34 in com.hhvvg.anydebug:layout/activity_main: Error inflating class androidx.fragment.app.FragmentContainerView
Caused by: java.lang.NullPointerException: <get-confService>(...) must not be null
	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.getConfService(SettingsFragment.kt:23)
	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreatePreferences(SettingsFragment.kt:47)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
	at com.hhvvg.anydebug.ui.fragment.SettingsFragment.onCreate(SettingsFragment.kt:36)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2773)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1913)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.kt:169)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2981)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1670)
	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
	at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.kt:158)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:53)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1098)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1026)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:61)
	at com.hhvvg.anydebug.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:55)
	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
	at com.hhvvg.anydebug.ui.MainActivity$binding$2.invoke(MainActivity.kt:11)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.hhvvg.anydebug.ui.MainActivity.getBinding(MainActivity.kt:11)
	at com.hhvvg.anydebug.ui.MainActivity.onCreate(MainActivity.kt:15)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3798)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3963)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2381)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8234)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by Miku-Y** [comment]
复议，MIUI14  安卓13启动闪退

**Comment by gitofleonardo** [comment]
最新版本已修复该问题
